---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: cc-api-output-auth
outputs:
  - name: cc-api-output-list-all-app-usage-events
run:
  path: cc-api-tests/tasks/list_all_app_usage_events/task.sh

params:
  INPUT: cc-api-output-auth
  OUTPUT: cc-api-output-list-all-app-usage-events
  PIPELINE:
  DATADOG_API_KEY:
  FOUNDATION:
  TASK: list_all_app_usage_events
