---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: readfrom
outputs:
  - name: buildstep

run:
  path: cc-api-tests/tasks/list_all_app_usage_events/task.sh

params:
  READFROM:
  BUILDSTEP:
  PIPELINE:
