---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: stevekaten/docker-pyresttest
    tag: '1.0'

inputs:
  - name: cc-api-tests
  - name: cc-api-tests-bucket

run:
  path: cc-api-tests/tasks/list_all_app_usage_events/task.sh
