---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: cc-api-tests-creating-an-app

run:
  path: cc-api-tests/tasks/get_app_summary/task.sh

params:
  PIPELINE:
