---
- config:
    - testset: "API"
    - generators:
        - 'cf_username': {type: 'env_variable', variable_name: 'CF_USERNAME'}
        - 'cf_password': {type: 'env_variable', variable_name: 'CF_PASSWORD'}
        - 'cf_client_id': {type: 'env_variable', variable_name: 'CF_CLIENT_ID'}
        - 'cf_login_url': {type: 'env_variable', variable_name: 'CF_LOGIN_URL'}
        - 'cf_api_url': {type: 'env_variable', variable_name: 'CF_API_URL'}

- test:
    - generator_binds: {cf_username: cf_username, cf_password: cf_password, cf_client_id: cf_client_id, cf_login_url: cf_login_url, cf_api_url: cf_api_url}
    - name: "Auth"
    - group: "get_token"
    - url: {template: "https://$cf_login_url/oauth/token?username=$cf_username&password=$cf_password&client_id=$cf_client_id&grant_type=password&response_type=token"}
    - method: "POST"
    - headers: {'Content-Type': 'application/json', 'Authorization': 'Basic Y2Y6'}
    - expected_status: [200]
    - extract_test: {jsonpath_mini: 'access_token', test: 'exists'}
    - extract_binds:
        - 'bearer_token': {'jsonpath_mini': 'access_token'}
- test:
    - name: "List App Usage Events"
    - group: "list_all_app_usage_events"
    - url: {template: "https://$cf_api_url/v2/app_usage_events"}
    - method: "GET"
    - headers: {template: {'Content-Type': 'application/json', 'Authorization': 'Bearer $bearer_token'}}
    - extract_binds:
        - 'guid': {'jsonpath_mini': 'resources.0.metadata.guid'}
- test:
    - name: "Retrieve a Particular App Usage Event"
    - group: "retrieve_a_particular_app_usage_event"
    - url: {template: "https://$cf_api_url/v2/app_usage_events/$guid"}
    - method: "GET"
    - headers: {template: {'Content-Type': 'application/json', 'Authorization': 'Bearer $bearer_token'}}
