---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: stevekaten/docker-pyresttest
    tag: '1.0'

inputs:
  - name: cc-api-tests
outputs:
  - name: cc-api-tests-put-bucket

run:
  path: cc-api-tests/tasks/auth/task.sh

params:
  USERNAME:
  PASSWORD:
  CLIENT_ID:
  LOGIN_URL:
  CF_API_URL:
