---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: '2-alpine'

inputs:
  - name: cc-api-tests

run:
  path: cc-api-tests/tasks/auth/task.sh

params:
  CF_USERNAME:
  CF_PASSWORD:
  CF_CLIENT_ID:
  CF_LOGIN_URL:
  CF_API_URL:
