---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: stevekaten/docker-pyresttest
    tag: '1.0'

inputs:
  - name: cc-api-tests
outputs:
  - name: cc-api-tests-bucket

run:
  path: cc-api-tests/tasks/auth/task.sh

params:
  CF_USERNAME:
  CF_PASSWORD:
  CF_CLIENT_ID:
  CF_LOGIN_URL:
  CF_API_URL:
