---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
outputs:
  - name: cc-api-output-auth

run:
  path: cc-api-tests/tasks/auth/task.sh

params:
  OUTPUT: cc-api-output-auth
  USERNAME:
  PASSWORD:
  CLIENT_ID:
  LOGIN_URL:
  CF_API_URL:
  PIPELINE:
