---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-output-auth
  - name: cc-api-tests
  - name: cc-api-tests-bucket

run:
  path: cc-api-tests/tasks/list_all_apps/task.sh

params:
  PIPELINE:
