resources:
- name: cc-api-tests
  type: git
  source:
    branch: master
    private_key: ((cc_api_tests_priv_key))
    uri: https://github.com/rackerlabs/cc-api-tests.git
- name: cc-api-tests-bucket
  type: s3
  source:
    bucket: cc-api-tests.atc.bubbleup.club
    region_name: us-west-2
    versioned_file: ((PIPELINE)).txt
    access_key_id: ((CC_API_TEST_ACCESS_KEY))
    secret_access_key: ((CC_API_TEST_SECRET_ACCESS_KEY))

jobs:
- name: setup
  serial: true
  serial_groups: [((PIPELINE))]
  plan:
  - get: cc-api-tests
    trigger: true
  - task: auth
    file: cc-api-tests/tasks/auth/task.yml
    params:
      USERNAME: ((USERNAME))
      PASSWORD: ((PASSWORD))
      CLIENT_ID: ((CLIENT_ID))
      LOGIN_URL: ((LOGIN_URL))
      CF_API_URL: ((CF_API_URL))
      PIPELINE: ((PIPELINE))
  - aggregate:
    - task: create-a-shared-domain
      file: cc-api-tests/tasks/create_a_shared_domain/task.yml
      params:
        PIPELINE: ((PIPELINE))
        DATADOG_API_KEY: ((DATADOG_API_KEY))
    - task: creating-an-organization
      file: cc-api-tests/tasks/creating_an_organization/task.yml
      params:
        PIPELINE: ((PIPELINE))
  - task: creating-a-space
    file: cc-api-tests/tasks/creating_a_space/task.yml
    params:
      PIPELINE: ((PIPELINE))
  - task: creating-a-route
    file: cc-api-tests/tasks/creating_a_route/task.yml
    params:
      PIPELINE: ((PIPELINE))
  - task: rollup-input
    file: cc-api-tests/tasks/rollup_input/task.yml
    params:
      PIPELINE: ((PIPELINE))
  - put: cc-api-tests-bucket
    params:
      file: cc-api-output-rollup-input/((PIPELINE)).txt

- name: test
  serial: true
  serial_groups: [((PIPELINE))]
  plan:
  - get: cc-api-tests
  - get: cc-api-tests-bucket
    trigger: true
    passed:
    - setup
  - task: auth
    file: cc-api-tests/tasks/auth/task.yml
    params:
      USERNAME: ((USERNAME))
      PASSWORD: ((PASSWORD))
      CLIENT_ID: ((CLIENT_ID))
      LOGIN_URL: ((LOGIN_URL))
      CF_API_URL: ((CF_API_URL))
      PIPELINE: ((PIPELINE))
  - task: creating-an-app
    file: cc-api-tests/tasks/creating_an_app/task.yml
    params:
      PIPELINE: ((PIPELINE))
    input_mapping: {cc-api-output-creating-a-space: cc-api-tests-bucket}
  - aggregate:
    - task: list-all-apps
      file: cc-api-tests/tasks/list_all_apps/task.yml
      params:
        PIPELINE: ((PIPELINE))
      input_mapping: {cc-api-output-creating-a-space: cc-api-tests-bucket}
    - task: get-app-summary
      file: cc-api-tests/tasks/get_app_summary/task.yml
      params:
        PIPELINE: ((PIPELINE))
    - task: list-all-routes-for-the-app
      file: cc-api-tests/tasks/list_all_routes_for_the_app/task.yml
      params:
        PIPELINE: ((PIPELINE))
    - task: list-all-service-bindings-for-the-app
      file: cc-api-tests/tasks/list_all_service_bindings_for_the_app/task.yml
      params:
        PIPELINE: ((PIPELINE))
    - task: retrieve-a-particular-app
      file: cc-api-tests/tasks/retrieve_a_particular_app/task.yml
      params:
        PIPELINE: ((PIPELINE))
    - task: retrieving-permissions-on-a-app
      file: cc-api-tests/tasks/retrieving_permissions_on_a_app/task.yml
      params:
        PIPELINE: ((PIPELINE))
    - task: get-the-env-for-an-app
      file: cc-api-tests/tasks/get_the_env_for_an_app/task.yml
      params:
        PIPELINE: ((PIPELINE))
  - task: associate-route-with-the-app
    file: cc-api-tests/tasks/associate_route_with_the_app/task.yml
    params:
      PIPELINE: ((PIPELINE))
    input_mapping: {cc-api-output-creating-a-route: cc-api-tests-bucket}
  - task: remove-route-from-the-app
    file: cc-api-tests/tasks/remove_route_from_the_app/task.yml
    params:
      PIPELINE: ((PIPELINE))
    input_mapping: {cc-api-output-creating-a-route: cc-api-tests-bucket}
  - task: delete-a-particular-app
    file: cc-api-tests/tasks/delete_a_particular_app/task.yml
    params:
      PIPELINE: ((PIPELINE))
  - task: rollup-input-apps-test
    file: cc-api-tests/tasks/rollup_input_apps_test/task.yml
    params:
      PIPELINE: ((PIPELINE))
  - put: cc-api-tests-bucket
    params:
      file: cc-api-output-rollup-input/((PIPELINE)).txt

- name: teardown
  serial: true
  serial_groups: [((PIPELINE))]
  plan:
  - get: cc-api-tests
  - get: cc-api-tests-bucket
    trigger: true
    passed:
    - test
  - task: auth
    file: cc-api-tests/tasks/auth/task.yml
    params:
      USERNAME: ((USERNAME))
      PASSWORD: ((PASSWORD))
      CLIENT_ID: ((CLIENT_ID))
      LOGIN_URL: ((LOGIN_URL))
      CF_API_URL: ((CF_API_URL))
      PIPELINE: ((PIPELINE))
  - task: delete-a-particular-route
    file: cc-api-tests/tasks/delete_a_particular_route/task.yml
    params:
      PIPELINE: ((PIPELINE))
    input_mapping: {cc-api-output-creating-a-route: cc-api-tests-bucket}
  - task: delete-a-particular-space
    file: cc-api-tests/tasks/delete_a_particular_space/task.yml
    params:
      PIPELINE: ((PIPELINE))
    input_mapping: {cc-api-output-creating-a-space: cc-api-tests-bucket}
  - task: delete-a-particular-organization
    file: cc-api-tests/tasks/delete_a_particular_organization/task.yml
    params:
      PIPELINE: ((PIPELINE))
    input_mapping: {cc-api-output-creating-an-organization: cc-api-tests-bucket}
