---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

run:
  path: cc-api-tests/tasks/on_failure/task.sh

params:
  PIPELINE:
  DATADOG_API_KEY:
  FOUNDATION:
  TASK:
