---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: cc-api-tests-put-bucket
run:
  path: cc-api-tests/tasks/retrieve_a_particular_app_usage_event/task.sh

params:
  PIPELINE:
