---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: cc-api-output-auth
  - name: cc-api-output-creating-an-app
  - name: cc-api-output-create-a-service-binding

run:
  path: cc-api-tests/tasks/remove_service_binding_from_the_app/task.sh

params:
  PIPELINE:
  DATADOG_API_KEY:
  FOUNDATION:
  TASK: remove_service_binding_from_the_app
