---
- config:
    - testset: "API"
    - generators:
        - 'cf_api_url': {type: 'env_variable', variable_name: 'CF_API_URL'}
        - 'auth_token': {type: 'env_variable', variable_name: 'AUTH_TOKEN'}

- test:
    - generator_binds: {cf_api_url: cf_api_url, auth_token: auth_token}
    - name: "remove-service-binding-from-the-app"
    - url: {template: "https://$cf_api_url/v2/apps/$cf_app_guid/service_bindings/$cf_service_binding_guid"}
    - method: "DELETE"
    - headers: {template: {'Content-Type': 'application/json', 'Authorization': 'Bearer $auth_token'}}
    - expected_status: [204]
