---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: cc-api-output-create-a-shared-domain
  - name: cc-api-output-creating-a-space
outputs:
  - name: cc-api-output-creating-a-route


run:
  path: cc-api-tests/tasks/creating_a_route/task.sh

params:
  PIPELINE:
