---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: cc-api-output-auth
  - name: cc-api-output-creating-an-app

run:
  path: cc-api-tests/tasks/get_detailed_stats_for_a_started_app/task.sh

params:
  PIPELINE:
  DATADOG_API_KEY:
  FOUNDATION:
  TASK: get_detailed_stats_for_a_started_app
