---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: cc-api-output-auth
outputs:
  - name: cc-api-output-create-a-shared-domain


run:
  path: cc-api-tests/tasks/create_a_shared_domain/task.sh

params:
  PIPELINE:
  INPUT: cc-api-output-auth
  OUTPUT: cc-api-output-create-a-shared-domain
