---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: cc-api-output-auth
  - name: cc-api-output-creating-an-app
  - name: cc-api-output-creating-a-user-provided-service-instance

run:
  path: cc-api-tests/tasks/delete_a_particular_user_provided_service_instance/task.sh

params:
  PIPELINE:
  DATADOG_API_KEY:
  FOUNDATION:
  TASK: delete_a_particular_user_provided_service_instance
