---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: cc-api-output-creating-a-space
  - name: cc-api-output-auth
outputs:
  - name: cc-api-output-creating-a-source-app

run:
  path: cc-api-tests/tasks/creating_a_source_app/task.sh

params:
  PIPELINE:
  OUTPUT: cc-api-output-creating-a-source-app
  DATADOG_API_KEY:
  FOUNDATION:
  TASK: creating_a_source_app
