resources:
- name: 15m
  type: time
  source: {interval: 15m}
- name: cc-api-tests
  type: git
  source:
    branch: master
    private_key: ((cc_api_tests_priv_key))
    uri: https://github.com/rackerlabs/cc-api-tests.git
- name: cc-api-tests-bucket
  type: s3
  source:
    bucket: cc-api-tests.atc.bubbleup.club
    region_name: ((REGION))
    versioned_file: app-usage-events.txt
    access_key_id: ((CC_API_TEST_ACCESS_KEY))
    secret_access_key: ((CC_API_TEST_SECRET_ACCESS_KEY))

jobs:
- name: setup
  serial: true
  serial_groups: [app-usage-events]
  plan:
  - get: 15m
    trigger: true
  - get: cc-api-tests
    trigger: true
  - task: auth
    file: cc-api-tests/tasks/auth/task.yml
    params:
      USERNAME: ((USERNAME))
      PASSWORD: ((PASSWORD))
      CLIENT_ID: ((CLIENT_ID))
      LOGIN_URL: ((LOGIN_URL))
      CF_API_URL: ((CF_API_URL))
      PIPELINE: ((PIPELINE))
  - put: cc-api-tests-bucket
    params:
      file: cc-api-output-auth/app-usage-events.txt

- name: test
  serial: true
  serial_groups: [app-usage-events]
  plan:
  - get: cc-api-tests
  - get: cc-api-tests-bucket
    trigger: true
    passed:
    - setup
  - task: auth
    file: cc-api-tests/tasks/auth/task.yml
    params:
      USERNAME: ((USERNAME))
      PASSWORD: ((PASSWORD))
      CLIENT_ID: ((CLIENT_ID))
      LOGIN_URL: ((LOGIN_URL))
      CF_API_URL: ((CF_API_URL))
      PIPELINE: ((PIPELINE))
  - task: list-all-app-usage-events
    file: cc-api-tests/tasks/list_all_app_usage_events/task.yml
    params:
      PIPELINE: ((PIPELINE))
    input_mapping: {cc-api-output-auth: cc-api-tests-bucket}
  - task: retrieve_a_particular_app_usage_event
    file: cc-api-tests/tasks/retrieve_a_particular_app_usage_event/task.yml
    params:
      PIPELINE: ((PIPELINE))
