resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource

resources:
- name: cc-api-tests
  type: git
  source:
    branch: master
    private_key: ((cc_api_tests_priv_key))
    uri: https://github.com/rackerlabs/cc-api-tests.git
- name: keyval
  type: keyval


jobs:
- name: auth-with-uaa
  plan:
  - get: cc-api-tests
    trigger: true
  - task: auth
    file: cc-api-tests/tasks/auth/task.yml
    params:
      CF_USERNAME: ((CF_USERNAME))
      CF_PASSWORD: ((CF_PASSWORD))
      CF_CLIENT_ID: ((CF_CLIENT_ID))
      CF_LOGIN_URL: ((CF_LOGIN_URL))
      CF_API_URL: ((CF_API_URL))
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: list-all-app-usage-events
  plan:
  - get: cc-api-tests
  - get: keyval
    trigger: true
    passed:
    - auth-with-uaa
  - task: list-all-app-usage-events
    file: cc-api-tests/tasks/list_all_app_usage_event/task.yml
