resources:
- name: cc-api-tests
  type: git
  source:
    branch: master
    private_key: ((cc_api_tests_priv_key))
    uri: https://github.com/rackerlabs/cc-api-tests.git
- name: cc-api-tests-bucket
  type: s3
  source:
    bucket: cc-api-tests.atc.bubbleup.club
    region: us-west-2
    versioned_file: app-usage-events.txt

jobs:
- name: auth-with-uaa
  plan:
  - get: cc-api-tests
    trigger: true
  - task: auth
    file: cc-api-tests/tasks/auth/task.yml
    params:
      CF_USERNAME: ((CF_USERNAME))
      CF_PASSWORD: ((CF_PASSWORD))
      CF_CLIENT_ID: ((CF_CLIENT_ID))
      CF_LOGIN_URL: ((CF_LOGIN_URL))
      CF_API_URL: ((CF_API_URL))
  - put: cc-api-tests-bucket
    params:
      file: cc-api-tests-bucket/app-usage-events.txt

- name: list-all-app-usage-events
  plan:
  - get: cc-api-tests
  - get: cc-api-tests-bucket
    trigger: true
    passed:
    - auth-with-uaa
  - task: list-all-app-usage-events
    file: cc-api-tests/tasks/list_all_app_usage_events/task.yml
