---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2


inputs:
  - name: cc-api-tests
  - name: cc-api-output-auth
outputs:
  - name: cc-api-output-creating-an-organization

run:
  path: cc-api-tests/tasks/creating_an_organization/task.sh

params:
  PIPELINE:
  OUTPUT: cc-api-output-creating-an-organization
  DATADOG_API_KEY:
  FOUNDATION:
  USERNAME:
  PASSWORD:
  CF_API_URL:
  TASK: creating_an_organization
