---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: cc-api-output-auth
outputs:
  - name: cc-api-output-creating-an-organization

run:
  path: cc-api-tests/tasks/creating_an_organization/task.sh

params:
  PIPELINE:
  INPUT: cc-api-output-auth
  OUTPUT: cc-api-output-creating-an-organization
