---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: cc-api-output-auth
  - name: cc-api-output-creating-an-app

run:
  path: cc-api-tests/tasks/terminate_the_running_app_instance_at_the_given_index/task.sh

params:
  PIPELINE:
  DATADOG_API_KEY:
  FOUNDATION:
  TASK: terminate_the_running_app_instance_at_the_given_index
