---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-tests
  - name: cc-api-tests-bucket

run:
  path: cc-api-tests/tasks/creating_a_space/task.sh

params:
  PIPELINE:
