---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/mpcf/cc-api-tests

inputs:
  - name: cc-api-output-auth
  - name: cc-api-tests
  - name: cc-api-output-creating-an-organization
outputs:
  - name: cc-api-output-creating-a-space

run:
  path: cc-api-tests/tasks/creating_a_space/task.sh

params:
  PIPELINE:
  INPUT: cc-api-output-creating-an-organization
  OUTPUT: cc-api-output-creating-a-space
